# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f08a4c31ac40df886bc96fa2e72845627865cbb8018f0d0c170dff8f35cd5f0030802f127cd78ae7ab39191f8692ac661ce9b3dc1135509005623a73275b381

test:
  secret_key_base: c349512b984299f2d966ec4b083a69513e2a4baf62747371058366702f4798a6f2a86458529ee60db63066120307666c421c687d8ab5ce8d22fc9cc5e6b64d4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
